#!/bin/bash 

# Based on a script by Ryan Tomayko
#   http://tomayko.com/writings/os-x-network-location-support-from-the-command-line

# get the current network location name
netloc=$(/usr/sbin/scselect 2>&1 | egrep '^ \* ' | \
         sed 's:.*(\(.*\)):\1:')

# find the proxy in /etc/http_proxy based on the 
# current location
http_proxy=$(egrep "$netloc[ \t]*=" ~/bin/dotfiles/misc/proxies | \
             sed 's/.*=[ \t]*\(.*\)[ \t]|[ \t]*\(.*\)/\1/')
no_proxy=$(egrep "$netloc[ \t]*=" ~/bin/dotfiles/misc/proxies | \
		     sed 's/.*=[ \t]*\(.*\)[ \t]|[ \t]*\(.*\)/\2/')

if [ -n "$http_proxy" ]; then
  export http_proxy
  export HTTP_PROXY="$http_proxy"
  export no_proxy
  export NO_PROXY="$no_proxy"
else
  unset http_proxy
  unset HTTP_PROXY
  unset no_proxy
  unset NO_PROXY
fi