#!/bin/sh

detect_rb=$DOT_FILES/misc/proxy_detect_osx.rb

proxy=$(ruby $detect_rb proxy)
no_proxy=$(ruby $detect_rb no_proxy)

if [ -n "$proxy" ]; then
  export proxy
  export http_proxy="http://$proxy"
  export HTTP_PROXY="$http_proxy"
  export no_proxy
  export NO_PROXY="$no_proxy"
else
  unset proxy
  unset http_proxy
  unset HTTP_PROXY
  unset no_proxy
  unset NO_PROXY
fi

unset detect_rb
