# Ruby GC Tuning

# MRI 2.1+
export RUBY_GC_HEAP_FREE_SLOTS=500000
export RUBY_GC_HEAP_GROWTH_FACTOR=1
# export RUBY_GC_HEAP_GROWTH_MAX_SLOTS=0
export RUBY_GC_HEAP_INIT_SLOTS=1000000
export RUBY_GC_HEAP_SLOTS_INCREMENT=1000000
export RUBY_GC_MALLOC_LIMIT=100000000 # Also REE / MRI 1.9 / MRI 2.0
# export RUBY_GC_MALLOC_LIMIT_GROWTH_FACTOR=0
# export RUBY_GC_MALLOC_LIMIT_MAX=0

# REE
export RUBY_HEAP_FREE_MIN=$RUBY_GC_HEAP_FREE_SLOTS
# export RUBY_HEAP_MIN_SLOTS=$RUBY_GC_HEAP_INIT_SLOTS # Deprecated in MRI 2.1
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=$RUBY_GC_HEAP_GROWTH_FACTOR
export RUBY_HEAP_SLOTS_INCREMENT=$RUBY_GC_HEAP_SLOTS_INCREMENT

# REE / MRI 1.9 / MRI 2.0 (Deprecated in MRI 2.1)
# export RUBY_FREE_MIN=$RUBY_GC_HEAP_FREE_SLOTS

# Default Ruby
chruby 2.2
