#!/usr/bin/env bash
#
# Installs dependencies
#
# NOTE: This should _not_ be run with Strap, since it bootstraps the Brewfile itself.
set -e
set -o pipefail

SCRIPT_ROOT=$(dirname "$0")
# shellcheck source=script/shared/settings.sh
source "${SCRIPT_ROOT}/shared/settings.sh"

install_dependencies
install_fonts

# Terminal settings
set_default_shell
set_terminal_settings
