#!/usr/bin/env bash
#
# Installs dependencies
#
# NOTE: Actually does nothing, since Strap is used to install dependencies.
set -e
set -o pipefail

DOT_FILES=$(git rev-parse --show-toplevel)
SCRIPT_ROOT="$DOT_FILES/script"

# shellcheck source=script/shared/common.sh
source "$SCRIPT_ROOT/shared/common.sh"

prompt="Dependencies are installed by Strap. Opening webpage to generate \`strap.sh\`."
url="https://strap.githubapp.com/"
open_url=false

confirm "$prompt" open_url
if [ "$open_url" = "true" ]; then
  open "$url"
  echo ''
else
  echo ''
  infon "Cancelled"
fi
