#!/bin/bash
#
# bootstrap installs things.

DOTFILES_ROOT="`pwd`"
source "${DOTFILES_ROOT}/script/shared/common.sh"
source "${DOTFILES_ROOT}/script/shared/generate_gitconfig.sh"

set -e

link_gitconfig() {
  src="${DOTFILES_ROOT}/git/gitconfig.symlink"
  dest="${HOME}/.gitconfig"

  if [ -f $dest ]
  then
    remove_file $dest
  fi

  link_file $src $dest
}

echo ''
generate_gitconfig
link_gitconfig
