#!/bin/bash
#
# install without user input

DOTFILES_ROOT="`pwd`"
source "${DOTFILES_ROOT}/script/shared/io_helpers.sh"
source "${DOTFILES_ROOT}/script/shared/uninstall.sh"

set -e

install_dotfiles() {
  info 'installing dotfiles'
  for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
  do
    dest="$HOME/.`basename \"${source%.*}\"`"

    ln -s $source $dest
    success "linked $source to $dest"
  done
}

echo ''
delete_all
install_dotfiles
echo ''
echo '   installed!'
