#!/usr/bin/env bash
#
# Remove dotfiles
set -e
set -o pipefail

SCRIPT_ROOT=$(dirname "$0")
# shellcheck source=script/shared/common.sh
source "$SCRIPT_ROOT/shared/common.sh"

# The '--complete' arg also deletes prerequisites
nuke_complete=false
[ "$1" = "--complete" ] && nuke_complete=true

nuke_confirmed=false
confirm 'About to nuke dotfiles setup!' nuke_confirmed

# Bail if not confirmed
if [ "$nuke_confirmed" = "false" ]; then
  successn "Aborted"
  exit
fi

#
# Nuke terminal and shell preferences
#
# shellcheck source=terminal/nuke
source "$DOT_FILES/terminal/nuke"

#
# Nuke prerequisites (reverses 'bootstrap')
#
if [ "$nuke_complete" = "true" ]; then
  # shellcheck source=script/shared/prerequisites.sh
  source "$SCRIPT_ROOT/shared/prerequisites.sh"

  fonts_rm
  dotfiles_rm
  gitconfig_rm
  code_dir_rm
fi

successn "Nuked!"
