#!/usr/bin/env bash
#
# Setup dotfiles
set -eu
set -o pipefail

SCRIPT_ROOT=$(dirname "$0")
# shellcheck source=script/shared/paths.sh
source "$SCRIPT_ROOT/shared/paths.sh"

#
# Terminal and shell preferences
#
# shellcheck source=terminal/setup
source "$DOT_FILES/terminal/setup"

#
# Sublime Text 3 preferences
#
# shellcheck source=sublime3/setup
source "$DOT_FILES/sublime3/setup"

#
# Ruby environment
#
# shellcheck source=ruby/setup
source "$DOT_FILES/ruby/setup"

#
# Node environment
#
# shellcheck source=node/setup
source "$DOT_FILES/node/setup"
