#!/usr/bin/env bash
#
# Setup dotfiles
set -eu
set -o pipefail

SCRIPT_ROOT=$(dirname "$0")
# shellcheck source=script/shared/paths.sh
source "$SCRIPT_ROOT/shared/paths.sh"

#
# Software
#
# shellcheck source=script/shared/software.sh
source "$SCRIPT_ROOT/shared/software.sh"
homebrew_bundle

#
# Terminal and shell preferences
#
# shellcheck source=terminal/setup
source "$DOT_FILES/terminal/setup"
