#!/usr/bin/env bash
#
# Update dependencies and settings
set -e
set -o pipefail

SCRIPT_ROOT=$(dirname "$0")

#
# Software
#
# shellcheck source=script/shared/software.sh
source "$SCRIPT_ROOT/shared/software.sh"
homebrew_bundle

successn "updated"
