#!/usr/bin/env bash
#
# Update dependencies and settings
set -e
set -o pipefail

if [ -z ${DOT_FILES+x} ]; then
  DOT_FILES="$(git rev-parse --show-toplevel)"
fi

#
# Software
#
# shellcheck source=homebrew/update
source "$DOT_FILES/homebrew/update"

#
# VSCode preferences
#
# shellcheck source=vscode/setup
source "$DOT_FILES/vscode/setup"

#
# Ruby environment
#
# shellcheck source=ruby/update
source "$DOT_FILES/ruby/update"

#
# Node environment
#
# shellcheck source=node/update
source "$DOT_FILES/node/update"
