#!/bin/sh

detect_rb=$DOT_FILES/misc/proxy_detect_osx.rb
detected=$(ruby $detect_rb --all)

proxy=$(echo $detected | cut -d'|' -f1)
no_proxy=$(echo $detected | cut -d'|' -f2)

if [ -n "$proxy" ]; then
  export proxy
  export http_proxy="http://$proxy"
  export HTTP_PROXY="$http_proxy"
  export https_proxy="http://$proxy"
  export HTTPS_PROXY="$https_proxy"
  export no_proxy
  export NO_PROXY="$no_proxy"
  export GIT_PROXY_COMMAND="$DOT_FILES/misc/git-proxy.rb"
else
  unset proxy
  unset http_proxy
  unset HTTP_PROXY
  unset https_proxy
  unset HTTPS_PROXY
  unset no_proxy
  unset NO_PROXY
  unset GIT_PROXY_COMMAND
fi

unset detected
unset detect_rb
