#!/usr/bin/env bash
#
# Configure terminal apps
set -e
set -o pipefail

if [ -z ${DOT_FILES+x} ]; then
  DOT_FILES="$(git rev-parse --show-toplevel)"
fi

# shellcheck source=terminal/terminal.sh
source "$DOT_FILES/terminal/terminal.sh"

shell_zsh
terminal_preferences
